Traceback (most recent call last):
  File "/home/conkas/conkas.py", line 137, in <module>
    main()
  File "/home/conkas/conkas.py", line 88, in main
    contracts = compile_files([filename])
  File "/usr/local/lib/python3.8/dist-packages/solcx/main.py", line 118, in compile_files
    stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/solcx/utils/string.py", line 78, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/solcx/wrapper.py", line 187, in solc_wrapper
    raise SolcError(
solcx.exceptions.SolcError: An error occurred during execution
> command: `/root/.solcx/solc-v0.4.22 --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,opcodes,userdoc ./0x0f7f8ca2c9b617b4dabb1a16c3e2dc5d83faf907.sol`
> return code: `1`
> stderr:

> stdout:
Invalid option to --combined-json: clone-bin

real	0m3.544s
user	0m3.293s
sys	0m0.214s
