
Traceback (most recent call last):
  File "/home/conkas/conkas.py", line 105, in main
    ssa = Recover(bytecode, edges=[], optimize=True)
  File "/home/conkas/rattle/recover.py", line 768, in __init__
    self.internal = InternalRecover(filedata, edges, optimize, split_functions)
  File "/home/conkas/rattle/recover.py", line 37, in __init__
    self.guarenteed_optimizations()
  File "/home/conkas/rattle/recover.py", line 674, in guarenteed_optimizations
    if reader.insn.is_push and reader.replace_uses_with(item):
  File "/home/conkas/rattle/ssa.py", line 397, in replace_uses_with
    reader.replace_argument(self.return_value, sv)
  File "/home/conkas/rattle/ssa.py", line 289, in replace_argument
    assert (self.insn.pops == len(self.arguments) or
AssertionError

real	0m31.676s
user	0m31.380s
sys	0m0.710s
